# zapret-test 0.6.5.3 native availability configuration
DPI_DOMAINS="youtube.com discord.com instagram.com facebook.com x.com linkedin.com rutracker.org digitalocean.com amnezia.org getoutline.org mailfence.com flibusta.is rezka.ag api.telegram.org play.google.com"
GEO_DOMAINS="spotify.com netflix.com patreon.com swagger.io snyk.io mongodb.com autodesk.com graylog.org redis.io copilot.microsoft.com"
RUSSIAN_IPERF_SOURCE="https://raw.githubusercontent.com/itdoginfo/russian-iperf3-servers/main/speedtest.sh"
DOH_URL="https://cloudflare-dns.com/dns-query"
DNS_TEST_DOMAINS="youtube.com discord.com rutracker.org openwrt.org github.com"
DNS_SYNTH_IP="127.0.0.42"
